apiVersion: v1
kind: Service

metadata:
  name: mywebsite-service

spec:
  selector:
    app: mywebsite

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mywebsite

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mywebsite

  template:
    metadata:
      labels:
        app: mywebsite

    spec:
      containers:
      - name: mywebsite
        image: gokumonkey/mywebsite:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 80
